### ISSUE TITLE
top bar and font size

### ISSUE THREAD

**Issue by jothi-prasath** [vinceliuice/MacVentura-kde#1]
i apply the theme in global theme settings and i enabled all options.
the top bar is not in maximum width and font size is weird  
![image](https://github.com/vinceliuice/MacVentura-kde/assets/64248628/b2d59a47-556b-403c-9478-ee6d760814f9)

**Comment by vinceliuice** [comment]
You need to adjust you panel size and better in line clock font size, because my display is 4k and I using 200% scaling

**Comment by vinceliuice** [comment]
Right click the clock on panel and open settings
![Screenshot_20230601_100317](https://github.com/vinceliuice/MacVentura-kde/assets/7604295/5a6b6648-0e5a-4536-a475-35873ef664b3)
