### ISSUE TITLE
SDDM MacVentura Light theme

### ISSUE THREAD

**Issue by orychalk** [vinceliuice/MacVentura-kde#4]
Hi, I love your themes 😄
I've been using them for a long time.

I just upgraded to Plasma 6 and saw that you updated the SDDM themes to be compatible.
I therefore did several tests with the light and dark version, but I systematically got errors.

```
The current theme cannot be loaded due to the errors below 
file://usr/share/sddm/themes/MacVentura-Light/Main.qml Library import require a version
```

Thanks in advance 😀

![SDDM MacVentura Light](https://github.com/vinceliuice/MacVentura-kde/assets/57261547/59b6d0ca-0d7a-4cee-ab69-9cfe6ae2053b)

**Comment by vinceliuice** [comment]
Run: `sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/MacVentura-Light/`

**Comment by orychalk** [comment]
Hi,
It's work with sddm-greeter-qt6, but not in real boot.

**Comment by orychalk** [comment]
I just retested on a freshly installed Manjaro on a virtual machine and I found the same problem.

**Comment by vinceliuice** [comment]
Fixed now

**Comment by orychalk** [comment]
Hello,
Great, I manually add QtVersion=6 in metadata.desktop, and It's Work 😀
Thanks a lot 👍️
