### ISSUE TITLE
Request for gtk version

### ISSUE THREAD

**Issue by noobmyq** [vinceliuice/MacVentura-kde#6]
Hi, 

Just wondering if there are plans for gtk version of this theme, and MacSonoma as well. Really like your themes!!!

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/WhiteSur-gtk-theme

**Comment by noobmyq** [comment]
yeah I am currently using this bigSur theme and I just wonder if there is a Ventura or newer version macos-like theme for gtk

**Comment by vinceliuice** [comment]
But theme on MacOS do not have changes, there is no need to make a ventura version

**Comment by noobmyq** [comment]
Oh I see, I was thinking that there might be some subtle differences since you make different versions for kde de.

**Comment by vinceliuice** [comment]
Wallpapers are different, so I need to make different versions for sddm theme and login backgrounds for kde de
