### ISSUE TITLE
Which extensions are you using for a perfect maccy KDE desktop?

### ISSUE THREAD

**Issue by carlosmintfan** [vinceliuice/MacVentura-kde#7]
Hi @vinceliuice, thank you for this awesome theme! Are you using something like extensions for global menu, dock etc.? Could you share your KDE mac setup as seen in the screenshots with me?

**Comment by vinceliuice** [comment]
Kde desktop have builtin global menu plugin, on plasma 5.0 you can use latte for the dock, but it's not working on plasma 6.0, on plasma 6.0 I just use the default bottom floating panel as a dock

**Comment by carlosmintfan** [comment]
Thanks!
